- name: Backup /etc/resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.backup-aio
    remote_src: true
    mode: '0644'

- name: Insert CoreDNS IP as nameserver
  lineinfile:
    path: /etc/resolv.conf
    insertbefore: '^nameserver'
    firstmatch: yes
    line: "nameserver {{ coredns_vm.ipaddr }}"

- name: Configure search
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^search'
    line: "search {{ config.cluster_domain }} {{ config.base_domain }}"
