---
- name: "create ssh keys"
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
  become: True

- name: "fetch all public ssh keys"
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys
  become: True

- name: "Set fact installer_ssh_key"
  set_fact:
          config: "{{ config | combine({item.key: item.value}) }}"
  with_items:
   - key: installer_ssh_key 
     value: "{{ssh_keys.stdout}}"
